### ISSUE TITLE
Mechanical Workshop

### ISSUE THREAD

**Issue by bdweber1** [ASU-ASCEND/Fall-2022#1]
Task List:

- [x] Presentation made
- [x] Materials assembled
- [x] Demonstration made
- [x] Presented to audience by 9/20

GanttStart: 2022-08-19
GanttDue: 2022-09-20

**Comment by darthtaterdude** [comment]
---
due: 2022-09-1
---

**Comment by darthtaterdude** [comment]
---
due: 2022-09-01
---

**Comment by darthtaterdude** [comment]
GanttStart: 2022-08-18

**Comment by darthtaterdude** [comment]
GanttEnd: 2022-09-01

**Comment by bdweber1** [comment]
Done
