### ISSUE TITLE
System Block Diagram

### ISSUE THREAD

**Issue by bdweber1** [ASU-ASCEND/Fall-2022#30]
Task List:
- [x] CMG System Block diagram done
- [x] Rotation wheels System Block diagram done

GanttStart: 2022-09-05
GanttDue: 2022-09-09

**Comment by bdweber1** [comment]
General System Block Diagram completed

**Comment by TameemAlsharif** [comment]
CMG System Block diagram DONE, Rotation wheels System Block diagram DONE. Changes can still be made, however, it is good enough to start on the next step. Files were uploaded in the System Block Diagram folder.
