### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by bdweber1** [ASU-ASCEND/Fall-2022#32]
Task List:

- [x] [ISIS Space 2U Structure](https://www.isispace.nl/product/2-unit-cubesat-structure/)
- [x] [CubeSat Kit Structures](http://www.cubesatkit.com/content/design.html)

GanttStart: 2022-09-05
GanttDue: 2022-09-30

**Comment by bdweber1** [comment]
1U for each science mission

**Comment by JoeyBuch** [comment]
Regarding CubeSat Kit Structures, where should modeling team go to find necessary dimensions? Stated 1U for each science mission: do we have 2 science missions? Can start, but unsure of constraints

**Comment by Johnny-Realman** [comment]
Is there any information from the previous team

**Comment by JoeyBuch** [comment]
Going to go off basis of 1U being 100x100 mm floor with 113.5mm height

**Comment by bdweber1** [comment]
Science Missions:
- 1U for the Meteorology science mission. Atmospheric profiling and the sensors needed for that.
- 1U for the Attitude Determination and Control System science mission.

Previous structure had no documentation (that's on me). Essentially was just slap a foam box together and move things around until they worked. No model constraints then.

1U basis is correct for 100mm x 100 mm floor and 113.5mm height.

**Comment by bdweber1** [comment]
Progress has been made. Will be updated in #17
