### ISSUE TITLE
Heating Element Transfer Function Modeling

### ISSUE THREAD

**Issue by n1nbendo** [ASU-ASCEND/Fall-2022#47]
Task List:

- [ ] Current to Temperature tests: [Link](https://www.adafruit.com/product/1481)
- [ ] Model heat flow rate from above results
- [ ] Determine what current is needed for the whole flight
- [ ] Model transfer function of unit: [Link](https://www.electricalengineeringinfo.com/2017/05/transfer-function-mathematical-model-thermal-system.html) 

GanttStart: 2022-09-28
GanttDue: 2022-10-21

**Comment by bdweber1** [comment]
Pushed back a week, being worked on as of 10/14
